### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by kenju** [kenju/kobela#5]
## Next Scope

- [ ] React Component minimal spec with enzyme or other testing framework
- [ ] webpack hot reload for compiling typescript

## And Next Scope

- [ ] User model/controller with spec
- [ ] deploy to heroku 

## Misc

- [ ] fix environment variables (e.g. NODE_ENV, PGUSER) is undefined in spec
- [ ] USER is not loaded in node-postgres library
- [ ] Refactor TypeScript interface
- [ ] improve validation spec/feature for invalid params/request body
